name: Announce Update
on:
  workflow_run:
    workflows: ['Publish', 'Publish Development']
    types: [completed]

jobs:
  announce:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: version
        uses: actions/github-script@v7
        with:
          script: |
            const package = require('./package.json');
            return package.version;
      
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Determine if this was a dev or prod release
          IS_DEV="${{ github.event.workflow_run.name == 'Publish Development' }}"
          VERSION="${{ steps.version.outputs.result }}"
          
          # Construct the message
          if [ "$IS_DEV" = "true" ]; then
            # Development release - no ping
            curl -H "Content-Type: application/json" -X POST $DISCORD_WEBHOOK -d '{
              "embeds": [{
                "title": "New Development Release",
                "description": "Development Version '"$VERSION"' has been published to npm",
                "color": 3447003,
                "fields": [
                  {
                    "name": "Installation",
                    "value": "```npm install @typhonjs@dev```"
                  }
                ],
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }]
            }'
          else
            # Production release - with ping
            curl -H "Content-Type: application/json" -X POST $DISCORD_WEBHOOK -d '{
              "content": "<@&1352405641464909834>",
              "embeds": [{
                "title": "New Release",
                "description": "Version '"$VERSION"' has been published to npm",
                "color": 5763719,
                "fields": [
                  {
                    "name": "Installation",
                    "value": "```npm install typhonjs@latest```"
                  }
                ],
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }]
            }'
          fi