name: Build CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: List Current Directory (DEBUGGING)
        run: ls && ls ..

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
