name: Build CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up pnpm
        run: npm i --location=global pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build
