name: Build CI

on: 
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # How can someone forget this?
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up pnpm
        run: npm i --location=global pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build
