name: Build CI

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up pnpm
        run: npm i -g pnpm@10

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build
