name: Publish
on:
    push:
        branches:
            - development
jobs:
    npm-publish:
        name: npm-publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: check
              uses: EndBug/version-check@v2.1.5
              with:
                  diff-search: true
            - name: Set up Node
              if: steps.check.outputs.changed == 'true'
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Set up pnpm
              if: steps.check.outputs.changed == 'true'
              run: npm i -g pnpm@10
            - name: Install
              if: steps.check.outputs.changed == 'true'
              run: pnpm install
            - name: Publish
              if: steps.check.outputs.changed == 'true'
              # We need --no-git-checks because we swap a boolean to allow more lax types
              # in the published package.
              run: pnpm publish --no-git-checks
              env:
                npm_config_//registry.npmjs.org/:_authToken: ${{ secrets.NPM_AUTH_TOKEN }}}